// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InnerRpcMessage.proto

package org.okraAx.v3.bean;

public interface ReqAuthOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.okraAx.v3.bean.ReqAuth)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *  授权密钥
   * </pre>
   *
   * <code>optional string key = 1;</code>
   */
  java.lang.String getKey();
  /**
   * <pre>
   *  授权密钥
   * </pre>
   *
   * <code>optional string key = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();
}
