// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protoc/include/google/protobuf/type.proto

package com.google.protobuf;

public interface OptionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.protobuf.Option)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The option's name. For example, `"java_package"`.
   * </pre>
   *
   * <code>optional string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   * The option's name. For example, `"java_package"`.
   * </pre>
   *
   * <code>optional string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * The option's value. For example, `"com.google.protobuf"`.
   * </pre>
   *
   * <code>optional .google.protobuf.Any value = 2;</code>
   */
  boolean hasValue();
  /**
   * <pre>
   * The option's value. For example, `"com.google.protobuf"`.
   * </pre>
   *
   * <code>optional .google.protobuf.Any value = 2;</code>
   */
  com.google.protobuf.Any getValue();
  /**
   * <pre>
   * The option's value. For example, `"com.google.protobuf"`.
   * </pre>
   *
   * <code>optional .google.protobuf.Any value = 2;</code>
   */
  com.google.protobuf.AnyOrBuilder getValueOrBuilder();
}
