// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BeanRoom.proto

package org.okraAx.v3.beans.room;

public interface MsgPlayerInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.okraAx.v3.MsgPlayerInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *  角色 唯一ID
   * </pre>
   *
   * <code>optional int64 uid = 1;</code>
   */
  long getUid();

  /**
   * <pre>
   *  角色名称
   * </pre>
   *
   * <code>optional string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   *  角色名称
   * </pre>
   *
   * <code>optional string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   *  形象
   * </pre>
   *
   * <code>optional int32 figure = 3;</code>
   */
  int getFigure();

  /**
   * <pre>
   *  扩展数据
   * </pre>
   *
   * <code>optional .org.okraAx.v3.AxAny ext = 4;</code>
   */
  boolean hasExt();
  /**
   * <pre>
   *  扩展数据
   * </pre>
   *
   * <code>optional .org.okraAx.v3.AxAny ext = 4;</code>
   */
  org.okraAx.v3.AxAnyProto.AxAny getExt();
  /**
   * <pre>
   *  扩展数据
   * </pre>
   *
   * <code>optional .org.okraAx.v3.AxAny ext = 4;</code>
   */
  org.okraAx.v3.AxAnyProto.AxAnyOrBuilder getExtOrBuilder();

  /**
   * <pre>
   *  道具数据
   * </pre>
   *
   * <code>map&lt;int32, int32&gt; items = 5;</code>
   */
  int getItemsCount();
  /**
   * <pre>
   *  道具数据
   * </pre>
   *
   * <code>map&lt;int32, int32&gt; items = 5;</code>
   */
  boolean containsItems(
      int key);
  /**
   * Use {@link #getItemsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, java.lang.Integer>
  getItems();
  /**
   * <pre>
   *  道具数据
   * </pre>
   *
   * <code>map&lt;int32, int32&gt; items = 5;</code>
   */
  java.util.Map<java.lang.Integer, java.lang.Integer>
  getItemsMap();
  /**
   * <pre>
   *  道具数据
   * </pre>
   *
   * <code>map&lt;int32, int32&gt; items = 5;</code>
   */

  int getItemsOrDefault(
      int key,
      int defaultValue);
  /**
   * <pre>
   *  道具数据
   * </pre>
   *
   * <code>map&lt;int32, int32&gt; items = 5;</code>
   */

  int getItemsOrThrow(
      int key);
}
