// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LoginPublicService.proto

package org.okraAx.v3.services;

public final class ProLoginPublic {
  private ProLoginPublic() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030LoginPublicService.proto\022\rorg.okraAx.v" +
      "3\032\tGpc.proto\032\020BeanPlayer.proto\032\020BeanComm" +
      "on.proto2\363\003\n\022LoginPublicService\022E\n\014onCre" +
      "ateRole\022\035.org.okraAx.v3.CreateRoleBean\032\026" +
      ".org.okraAx.v3.GpcVoid\022;\n\007onLogin\022\030.org." +
      "okraAx.v3.LoginBean\032\026.org.okraAx.v3.GpcV" +
      "oid\022<\n\nonSyncTime\022\026.org.okraAx.v3.GpcVoi" +
      "d\032\026.org.okraAx.v3.GpcVoid\022C\n\021onShowChann" +
      "elList\022\026.org.okraAx.v3.GpcVoid\032\026.org.okr" +
      "aAx.v3.GpcVoid\022@\n\016onEnterChannel\022\026.org.o",
      "kraAx.v3.GpcVoid\032\026.org.okraAx.v3.GpcVoid" +
      "\022C\n\021onGetLogReportUrl\022\026.org.okraAx.v3.Gp" +
      "cVoid\032\026.org.okraAx.v3.GpcVoid\022O\n\021onRepor" +
      "tClientLog\022\".org.okraAx.v3.ReportClientL" +
      "ogBean\032\026.org.okraAx.v3.GpcVoidB*\n\026org.ok" +
      "raAx.v3.servicesB\016ProLoginPublicH\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.okraAx.v3.Gpc.getDescriptor(),
          org.okraAx.v3.beans.player.GpcBnPlayer.getDescriptor(),
          org.okraAx.v3.beans.common.GpcBnCommon.getDescriptor(),
        }, assigner);
    org.okraAx.v3.Gpc.getDescriptor();
    org.okraAx.v3.beans.player.GpcBnPlayer.getDescriptor();
    org.okraAx.v3.beans.common.GpcBnCommon.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
