// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerCallbackFromRoom.proto

package org.okraAx.v3.services;

public final class ProPlayerRoomCallback {
  private ProPlayerRoomCallback() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034PlayerCallbackFromRoom.proto\022\rorg.okra" +
      "Ax.v3\032\tGpc.proto\032\020BeanPlayer.proto2P\n\026Pl" +
      "ayerCallbackFromRoom\0226\n\004pong\022\026.org.okraA" +
      "x.v3.GpcVoid\032\026.org.okraAx.v3.GpcVoidB1\n\026" +
      "org.okraAx.v3.servicesB\025ProPlayerRoomCal" +
      "lbackH\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.okraAx.v3.Gpc.getDescriptor(),
          org.okraAx.v3.beans.player.GpcBnPlayer.getDescriptor(),
        }, assigner);
    org.okraAx.v3.Gpc.getDescriptor();
    org.okraAx.v3.beans.player.GpcBnPlayer.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
