// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RoomForLoginService.proto

package org.okraAx.v3.services;

public final class ProRoomForLogin {
  private ProRoomForLogin() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031RoomForLoginService.proto\022\rorg.okraAx." +
      "v3\032\tGpc.proto2\345\001\n\023RoomForLoginService\022>\n" +
      "\014enterChannel\022\026.org.okraAx.v3.GpcVoid\032\026." +
      "org.okraAx.v3.GpcVoid\022J\n\030callbackVerifyP" +
      "layerAuth\022\026.org.okraAx.v3.GpcVoid\032\026.org." +
      "okraAx.v3.GpcVoid\022B\n\020callbackRegister\022\026." +
      "org.okraAx.v3.GpcVoid\032\026.org.okraAx.v3.Gp" +
      "cVoidB+\n\026org.okraAx.v3.servicesB\017ProRoom" +
      "ForLoginH\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.okraAx.v3.Gpc.getDescriptor(),
        }, assigner);
    org.okraAx.v3.Gpc.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
