// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BeanPlayer.proto

package org.okraAx.v3.beans.player;

public interface CallbackLoginBeanOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.okraAx.v3.CallbackLoginBean)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string openId = 1;</code>
   */
  java.lang.String getOpenId();
  /**
   * <code>optional string openId = 1;</code>
   */
  com.google.protobuf.ByteString
      getOpenIdBytes();
}
