// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BeanPlayer.proto

package org.okraAx.v3.beans.player;

public interface CallbackCreateRoleBeanOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.okraAx.v3.CallbackCreateRoleBean)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string openId = 1;</code>
   */
  java.lang.String getOpenId();
  /**
   * <code>optional string openId = 1;</code>
   */
  com.google.protobuf.ByteString
      getOpenIdBytes();

  /**
   * <code>optional string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional int32 figure = 3;</code>
   */
  int getFigure();
}
