// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BeanPlayer.proto

package org.okraAx.v3.beans.player;

public interface RetBeanOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.okraAx.v3.RetBean)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 ret = 1;</code>
   */
  int getRet();
}
