// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FyChessMessage.proto

package org.okraAx.v3.chess.beans;

public interface MsgChessMoveOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.okraAx.v3.MsgChessMove)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *  移动前x坐标轴
   * </pre>
   *
   * <code>optional int32 fromX = 1;</code>
   */
  int getFromX();

  /**
   * <code>optional int32 fromY = 2;</code>
   */
  int getFromY();

  /**
   * <code>optional int32 toX = 3;</code>
   */
  int getToX();

  /**
   * <code>optional int32 toY = 4;</code>
   */
  int getToY();
}
