// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FyChessMessage.proto

package org.okraAx.v3.chess.beans;

public interface PushChessInitOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.okraAx.v3.PushChessInit)
    com.google.protobuf.MessageOrBuilder {
}
