// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FyChessMessage.proto

package org.okraAx.v3.chess.beans;

public interface ResChessMoveOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.okraAx.v3.ResChessMove)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *  是否可以移动
   * </pre>
   *
   * <code>optional bool movable = 1;</code>
   */
  boolean getMovable();
}
