// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FyChessMessage.proto

package org.okraAx.v3.chess.beans;

public interface ResChessRoomInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.okraAx.v3.ResChessRoomInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .org.okraAx.v3.ResChessRoomInfo.RoomInfo infos = 1;</code>
   */
  java.util.List<org.okraAx.v3.chess.beans.ResChessRoomInfo.RoomInfo> 
      getInfosList();
  /**
   * <code>repeated .org.okraAx.v3.ResChessRoomInfo.RoomInfo infos = 1;</code>
   */
  org.okraAx.v3.chess.beans.ResChessRoomInfo.RoomInfo getInfos(int index);
  /**
   * <code>repeated .org.okraAx.v3.ResChessRoomInfo.RoomInfo infos = 1;</code>
   */
  int getInfosCount();
  /**
   * <code>repeated .org.okraAx.v3.ResChessRoomInfo.RoomInfo infos = 1;</code>
   */
  java.util.List<? extends org.okraAx.v3.chess.beans.ResChessRoomInfo.RoomInfoOrBuilder> 
      getInfosOrBuilderList();
  /**
   * <code>repeated .org.okraAx.v3.ResChessRoomInfo.RoomInfo infos = 1;</code>
   */
  org.okraAx.v3.chess.beans.ResChessRoomInfo.RoomInfoOrBuilder getInfosOrBuilder(
      int index);
}
