// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FyChessMessage.proto

package org.okraAx.v3.chess.beans;

public interface ResChessJoinOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.okraAx.v3.ResChessJoin)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *  阵营
   * </pre>
   *
   * <code>optional int32 side = 1;</code>
   */
  int getSide();
}
