// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AxRpcV3.proto

package org.okraAx.v3;

public final class AxRpc {
  private AxRpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_okraAx_v3_Rpc_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_okraAx_v3_Rpc_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_okraAx_v3_RpcError_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_okraAx_v3_RpcError_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_okraAx_v3_RpcVoid_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_okraAx_v3_RpcVoid_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rAxRpcV3.proto\022\rorg.okraAx.v3\032\013AxAny.pr" +
      "oto\032\017AxOptions.proto\"B\n\003Rpc\022\n\n\002id\030\001 \001(\005\022" +
      "\013\n\003api\030\002 \001(\005\022\"\n\004data\030\003 \001(\0132\024.org.okraAx." +
      "v3.AxAny\"+\n\010RpcError\022\r\n\005state\030\001 \001(\005\022\013\n\003m" +
      "sg\030\002 \001(\t:\003\300>\001\"\t\n\007RpcVoidB\032\n\rorg.okraAx.v" +
      "3B\005AxRpcH\001P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.okraAx.v3.AxAnyProto.getDescriptor(),
          org.okraAx.v3.AxOptions.getDescriptor(),
        }, assigner);
    internal_static_org_okraAx_v3_Rpc_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_okraAx_v3_Rpc_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_okraAx_v3_Rpc_descriptor,
        new java.lang.String[] { "Id", "Api", "Data", });
    internal_static_org_okraAx_v3_RpcError_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_okraAx_v3_RpcError_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_okraAx_v3_RpcError_descriptor,
        new java.lang.String[] { "State", "Msg", });
    internal_static_org_okraAx_v3_RpcVoid_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_okraAx_v3_RpcVoid_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_okraAx_v3_RpcVoid_descriptor,
        new java.lang.String[] { });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(org.okraAx.v3.AxOptions.messageId);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    org.okraAx.v3.AxAnyProto.getDescriptor();
    org.okraAx.v3.AxOptions.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
