// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExamplePublicService.proto

package org.okraAx.v3;

public final class ExamplePublicProto {
  private ExamplePublicProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MsgAuthOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.okraAx.v3.MsgAuth)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *  请求源
     * </pre>
     *
     * <code>optional int64 source = 1;</code>
     */
    long getSource();

    /**
     * <pre>
     *  授权密钥
     * </pre>
     *
     * <code>optional string key = 2;</code>
     */
    java.lang.String getKey();
    /**
     * <pre>
     *  授权密钥
     * </pre>
     *
     * <code>optional string key = 2;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();
  }
  /**
   * <pre>
   *  登录
   * </pre>
   *
   * Protobuf type {@code org.okraAx.v3.MsgAuth}
   */
  public  static final class MsgAuth extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.okraAx.v3.MsgAuth)
      MsgAuthOrBuilder {
    // Use MsgAuth.newBuilder() to construct.
    private MsgAuth(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MsgAuth() {
      source_ = 0L;
      key_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MsgAuth(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              source_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              key_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.okraAx.v3.ExamplePublicProto.internal_static_org_okraAx_v3_MsgAuth_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.okraAx.v3.ExamplePublicProto.internal_static_org_okraAx_v3_MsgAuth_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.okraAx.v3.ExamplePublicProto.MsgAuth.class, org.okraAx.v3.ExamplePublicProto.MsgAuth.Builder.class);
    }

    public static final int SOURCE_FIELD_NUMBER = 1;
    private long source_;
    /**
     * <pre>
     *  请求源
     * </pre>
     *
     * <code>optional int64 source = 1;</code>
     */
    public long getSource() {
      return source_;
    }

    public static final int KEY_FIELD_NUMBER = 2;
    private volatile java.lang.Object key_;
    /**
     * <pre>
     *  授权密钥
     * </pre>
     *
     * <code>optional string key = 2;</code>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *  授权密钥
     * </pre>
     *
     * <code>optional string key = 2;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (source_ != 0L) {
        output.writeInt64(1, source_);
      }
      if (!getKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, key_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (source_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, source_);
      }
      if (!getKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, key_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.okraAx.v3.ExamplePublicProto.MsgAuth)) {
        return super.equals(obj);
      }
      org.okraAx.v3.ExamplePublicProto.MsgAuth other = (org.okraAx.v3.ExamplePublicProto.MsgAuth) obj;

      boolean result = true;
      result = result && (getSource()
          == other.getSource());
      result = result && getKey()
          .equals(other.getKey());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + SOURCE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSource());
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.okraAx.v3.ExamplePublicProto.MsgAuth parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.okraAx.v3.ExamplePublicProto.MsgAuth parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.okraAx.v3.ExamplePublicProto.MsgAuth parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.okraAx.v3.ExamplePublicProto.MsgAuth parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.okraAx.v3.ExamplePublicProto.MsgAuth parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.okraAx.v3.ExamplePublicProto.MsgAuth parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.okraAx.v3.ExamplePublicProto.MsgAuth parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.okraAx.v3.ExamplePublicProto.MsgAuth parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.okraAx.v3.ExamplePublicProto.MsgAuth parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.okraAx.v3.ExamplePublicProto.MsgAuth parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.okraAx.v3.ExamplePublicProto.MsgAuth prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *  登录
     * </pre>
     *
     * Protobuf type {@code org.okraAx.v3.MsgAuth}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.okraAx.v3.MsgAuth)
        org.okraAx.v3.ExamplePublicProto.MsgAuthOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.okraAx.v3.ExamplePublicProto.internal_static_org_okraAx_v3_MsgAuth_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.okraAx.v3.ExamplePublicProto.internal_static_org_okraAx_v3_MsgAuth_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.okraAx.v3.ExamplePublicProto.MsgAuth.class, org.okraAx.v3.ExamplePublicProto.MsgAuth.Builder.class);
      }

      // Construct using org.okraAx.v3.ExamplePublicProto.MsgAuth.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        source_ = 0L;

        key_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.okraAx.v3.ExamplePublicProto.internal_static_org_okraAx_v3_MsgAuth_descriptor;
      }

      public org.okraAx.v3.ExamplePublicProto.MsgAuth getDefaultInstanceForType() {
        return org.okraAx.v3.ExamplePublicProto.MsgAuth.getDefaultInstance();
      }

      public org.okraAx.v3.ExamplePublicProto.MsgAuth build() {
        org.okraAx.v3.ExamplePublicProto.MsgAuth result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.okraAx.v3.ExamplePublicProto.MsgAuth buildPartial() {
        org.okraAx.v3.ExamplePublicProto.MsgAuth result = new org.okraAx.v3.ExamplePublicProto.MsgAuth(this);
        result.source_ = source_;
        result.key_ = key_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.okraAx.v3.ExamplePublicProto.MsgAuth) {
          return mergeFrom((org.okraAx.v3.ExamplePublicProto.MsgAuth)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.okraAx.v3.ExamplePublicProto.MsgAuth other) {
        if (other == org.okraAx.v3.ExamplePublicProto.MsgAuth.getDefaultInstance()) return this;
        if (other.getSource() != 0L) {
          setSource(other.getSource());
        }
        if (!other.getKey().isEmpty()) {
          key_ = other.key_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.okraAx.v3.ExamplePublicProto.MsgAuth parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.okraAx.v3.ExamplePublicProto.MsgAuth) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long source_ ;
      /**
       * <pre>
       *  请求源
       * </pre>
       *
       * <code>optional int64 source = 1;</code>
       */
      public long getSource() {
        return source_;
      }
      /**
       * <pre>
       *  请求源
       * </pre>
       *
       * <code>optional int64 source = 1;</code>
       */
      public Builder setSource(long value) {
        
        source_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  请求源
       * </pre>
       *
       * <code>optional int64 source = 1;</code>
       */
      public Builder clearSource() {
        
        source_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object key_ = "";
      /**
       * <pre>
       *  授权密钥
       * </pre>
       *
       * <code>optional string key = 2;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *  授权密钥
       * </pre>
       *
       * <code>optional string key = 2;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *  授权密钥
       * </pre>
       *
       * <code>optional string key = 2;</code>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  授权密钥
       * </pre>
       *
       * <code>optional string key = 2;</code>
       */
      public Builder clearKey() {
        
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  授权密钥
       * </pre>
       *
       * <code>optional string key = 2;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        key_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:org.okraAx.v3.MsgAuth)
    }

    // @@protoc_insertion_point(class_scope:org.okraAx.v3.MsgAuth)
    private static final org.okraAx.v3.ExamplePublicProto.MsgAuth DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.okraAx.v3.ExamplePublicProto.MsgAuth();
    }

    public static org.okraAx.v3.ExamplePublicProto.MsgAuth getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MsgAuth>
        PARSER = new com.google.protobuf.AbstractParser<MsgAuth>() {
      public MsgAuth parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MsgAuth(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MsgAuth> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MsgAuth> getParserForType() {
      return PARSER;
    }

    public org.okraAx.v3.ExamplePublicProto.MsgAuth getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MsgNodeInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.okraAx.v3.MsgNodeInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *模块
     * </pre>
     *
     * <code>optional int32 module = 1;</code>
     */
    int getModule();

    /**
     * <pre>
     *  组件唯一ID
     * </pre>
     *
     * <code>optional int64 id = 2;</code>
     */
    long getId();

    /**
     * <pre>
     *  组件的host地址
     * </pre>
     *
     * <code>optional string host = 3;</code>
     */
    java.lang.String getHost();
    /**
     * <pre>
     *  组件的host地址
     * </pre>
     *
     * <code>optional string host = 3;</code>
     */
    com.google.protobuf.ByteString
        getHostBytes();

    /**
     * <pre>
     *  组件内部监听端口
     * </pre>
     *
     * <code>optional int32 port = 4;</code>
     */
    int getPort();

    /**
     * <pre>
     *  组件绑定外部监听端口
     * </pre>
     *
     * <code>optional int32 bind = 5;</code>
     */
    int getBind();
  }
  /**
   * <pre>
   * 组件信息
   * </pre>
   *
   * Protobuf type {@code org.okraAx.v3.MsgNodeInfo}
   */
  public  static final class MsgNodeInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.okraAx.v3.MsgNodeInfo)
      MsgNodeInfoOrBuilder {
    // Use MsgNodeInfo.newBuilder() to construct.
    private MsgNodeInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MsgNodeInfo() {
      module_ = 0;
      id_ = 0L;
      host_ = "";
      port_ = 0;
      bind_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MsgNodeInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              module_ = input.readInt32();
              break;
            }
            case 16: {

              id_ = input.readInt64();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              host_ = s;
              break;
            }
            case 32: {

              port_ = input.readInt32();
              break;
            }
            case 40: {

              bind_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.okraAx.v3.ExamplePublicProto.internal_static_org_okraAx_v3_MsgNodeInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.okraAx.v3.ExamplePublicProto.internal_static_org_okraAx_v3_MsgNodeInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.okraAx.v3.ExamplePublicProto.MsgNodeInfo.class, org.okraAx.v3.ExamplePublicProto.MsgNodeInfo.Builder.class);
    }

    public static final int MODULE_FIELD_NUMBER = 1;
    private int module_;
    /**
     * <pre>
     *模块
     * </pre>
     *
     * <code>optional int32 module = 1;</code>
     */
    public int getModule() {
      return module_;
    }

    public static final int ID_FIELD_NUMBER = 2;
    private long id_;
    /**
     * <pre>
     *  组件唯一ID
     * </pre>
     *
     * <code>optional int64 id = 2;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int HOST_FIELD_NUMBER = 3;
    private volatile java.lang.Object host_;
    /**
     * <pre>
     *  组件的host地址
     * </pre>
     *
     * <code>optional string host = 3;</code>
     */
    public java.lang.String getHost() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        host_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *  组件的host地址
     * </pre>
     *
     * <code>optional string host = 3;</code>
     */
    public com.google.protobuf.ByteString
        getHostBytes() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        host_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 4;
    private int port_;
    /**
     * <pre>
     *  组件内部监听端口
     * </pre>
     *
     * <code>optional int32 port = 4;</code>
     */
    public int getPort() {
      return port_;
    }

    public static final int BIND_FIELD_NUMBER = 5;
    private int bind_;
    /**
     * <pre>
     *  组件绑定外部监听端口
     * </pre>
     *
     * <code>optional int32 bind = 5;</code>
     */
    public int getBind() {
      return bind_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (module_ != 0) {
        output.writeInt32(1, module_);
      }
      if (id_ != 0L) {
        output.writeInt64(2, id_);
      }
      if (!getHostBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, host_);
      }
      if (port_ != 0) {
        output.writeInt32(4, port_);
      }
      if (bind_ != 0) {
        output.writeInt32(5, bind_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (module_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, module_);
      }
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, id_);
      }
      if (!getHostBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, host_);
      }
      if (port_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, port_);
      }
      if (bind_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, bind_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.okraAx.v3.ExamplePublicProto.MsgNodeInfo)) {
        return super.equals(obj);
      }
      org.okraAx.v3.ExamplePublicProto.MsgNodeInfo other = (org.okraAx.v3.ExamplePublicProto.MsgNodeInfo) obj;

      boolean result = true;
      result = result && (getModule()
          == other.getModule());
      result = result && (getId()
          == other.getId());
      result = result && getHost()
          .equals(other.getHost());
      result = result && (getPort()
          == other.getPort());
      result = result && (getBind()
          == other.getBind());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + MODULE_FIELD_NUMBER;
      hash = (53 * hash) + getModule();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + HOST_FIELD_NUMBER;
      hash = (53 * hash) + getHost().hashCode();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort();
      hash = (37 * hash) + BIND_FIELD_NUMBER;
      hash = (53 * hash) + getBind();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.okraAx.v3.ExamplePublicProto.MsgNodeInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.okraAx.v3.ExamplePublicProto.MsgNodeInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.okraAx.v3.ExamplePublicProto.MsgNodeInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.okraAx.v3.ExamplePublicProto.MsgNodeInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.okraAx.v3.ExamplePublicProto.MsgNodeInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.okraAx.v3.ExamplePublicProto.MsgNodeInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.okraAx.v3.ExamplePublicProto.MsgNodeInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.okraAx.v3.ExamplePublicProto.MsgNodeInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.okraAx.v3.ExamplePublicProto.MsgNodeInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.okraAx.v3.ExamplePublicProto.MsgNodeInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.okraAx.v3.ExamplePublicProto.MsgNodeInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 组件信息
     * </pre>
     *
     * Protobuf type {@code org.okraAx.v3.MsgNodeInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.okraAx.v3.MsgNodeInfo)
        org.okraAx.v3.ExamplePublicProto.MsgNodeInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.okraAx.v3.ExamplePublicProto.internal_static_org_okraAx_v3_MsgNodeInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.okraAx.v3.ExamplePublicProto.internal_static_org_okraAx_v3_MsgNodeInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.okraAx.v3.ExamplePublicProto.MsgNodeInfo.class, org.okraAx.v3.ExamplePublicProto.MsgNodeInfo.Builder.class);
      }

      // Construct using org.okraAx.v3.ExamplePublicProto.MsgNodeInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        module_ = 0;

        id_ = 0L;

        host_ = "";

        port_ = 0;

        bind_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.okraAx.v3.ExamplePublicProto.internal_static_org_okraAx_v3_MsgNodeInfo_descriptor;
      }

      public org.okraAx.v3.ExamplePublicProto.MsgNodeInfo getDefaultInstanceForType() {
        return org.okraAx.v3.ExamplePublicProto.MsgNodeInfo.getDefaultInstance();
      }

      public org.okraAx.v3.ExamplePublicProto.MsgNodeInfo build() {
        org.okraAx.v3.ExamplePublicProto.MsgNodeInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.okraAx.v3.ExamplePublicProto.MsgNodeInfo buildPartial() {
        org.okraAx.v3.ExamplePublicProto.MsgNodeInfo result = new org.okraAx.v3.ExamplePublicProto.MsgNodeInfo(this);
        result.module_ = module_;
        result.id_ = id_;
        result.host_ = host_;
        result.port_ = port_;
        result.bind_ = bind_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.okraAx.v3.ExamplePublicProto.MsgNodeInfo) {
          return mergeFrom((org.okraAx.v3.ExamplePublicProto.MsgNodeInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.okraAx.v3.ExamplePublicProto.MsgNodeInfo other) {
        if (other == org.okraAx.v3.ExamplePublicProto.MsgNodeInfo.getDefaultInstance()) return this;
        if (other.getModule() != 0) {
          setModule(other.getModule());
        }
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getHost().isEmpty()) {
          host_ = other.host_;
          onChanged();
        }
        if (other.getPort() != 0) {
          setPort(other.getPort());
        }
        if (other.getBind() != 0) {
          setBind(other.getBind());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.okraAx.v3.ExamplePublicProto.MsgNodeInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.okraAx.v3.ExamplePublicProto.MsgNodeInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int module_ ;
      /**
       * <pre>
       *模块
       * </pre>
       *
       * <code>optional int32 module = 1;</code>
       */
      public int getModule() {
        return module_;
      }
      /**
       * <pre>
       *模块
       * </pre>
       *
       * <code>optional int32 module = 1;</code>
       */
      public Builder setModule(int value) {
        
        module_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *模块
       * </pre>
       *
       * <code>optional int32 module = 1;</code>
       */
      public Builder clearModule() {
        
        module_ = 0;
        onChanged();
        return this;
      }

      private long id_ ;
      /**
       * <pre>
       *  组件唯一ID
       * </pre>
       *
       * <code>optional int64 id = 2;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <pre>
       *  组件唯一ID
       * </pre>
       *
       * <code>optional int64 id = 2;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  组件唯一ID
       * </pre>
       *
       * <code>optional int64 id = 2;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object host_ = "";
      /**
       * <pre>
       *  组件的host地址
       * </pre>
       *
       * <code>optional string host = 3;</code>
       */
      public java.lang.String getHost() {
        java.lang.Object ref = host_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          host_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *  组件的host地址
       * </pre>
       *
       * <code>optional string host = 3;</code>
       */
      public com.google.protobuf.ByteString
          getHostBytes() {
        java.lang.Object ref = host_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          host_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *  组件的host地址
       * </pre>
       *
       * <code>optional string host = 3;</code>
       */
      public Builder setHost(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        host_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  组件的host地址
       * </pre>
       *
       * <code>optional string host = 3;</code>
       */
      public Builder clearHost() {
        
        host_ = getDefaultInstance().getHost();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  组件的host地址
       * </pre>
       *
       * <code>optional string host = 3;</code>
       */
      public Builder setHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        host_ = value;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <pre>
       *  组件内部监听端口
       * </pre>
       *
       * <code>optional int32 port = 4;</code>
       */
      public int getPort() {
        return port_;
      }
      /**
       * <pre>
       *  组件内部监听端口
       * </pre>
       *
       * <code>optional int32 port = 4;</code>
       */
      public Builder setPort(int value) {
        
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  组件内部监听端口
       * </pre>
       *
       * <code>optional int32 port = 4;</code>
       */
      public Builder clearPort() {
        
        port_ = 0;
        onChanged();
        return this;
      }

      private int bind_ ;
      /**
       * <pre>
       *  组件绑定外部监听端口
       * </pre>
       *
       * <code>optional int32 bind = 5;</code>
       */
      public int getBind() {
        return bind_;
      }
      /**
       * <pre>
       *  组件绑定外部监听端口
       * </pre>
       *
       * <code>optional int32 bind = 5;</code>
       */
      public Builder setBind(int value) {
        
        bind_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  组件绑定外部监听端口
       * </pre>
       *
       * <code>optional int32 bind = 5;</code>
       */
      public Builder clearBind() {
        
        bind_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:org.okraAx.v3.MsgNodeInfo)
    }

    // @@protoc_insertion_point(class_scope:org.okraAx.v3.MsgNodeInfo)
    private static final org.okraAx.v3.ExamplePublicProto.MsgNodeInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.okraAx.v3.ExamplePublicProto.MsgNodeInfo();
    }

    public static org.okraAx.v3.ExamplePublicProto.MsgNodeInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MsgNodeInfo>
        PARSER = new com.google.protobuf.AbstractParser<MsgNodeInfo>() {
      public MsgNodeInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MsgNodeInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MsgNodeInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MsgNodeInfo> getParserForType() {
      return PARSER;
    }

    public org.okraAx.v3.ExamplePublicProto.MsgNodeInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_okraAx_v3_MsgAuth_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_okraAx_v3_MsgAuth_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_okraAx_v3_MsgNodeInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_okraAx_v3_MsgNodeInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032ExamplePublicService.proto\022\rorg.okraAx" +
      ".v3\032(protoc/include/google/protobuf/any." +
      "proto\032\017AxOptions.proto\"&\n\007MsgAuth\022\016\n\006sou" +
      "rce\030\001 \001(\003\022\013\n\003key\030\002 \001(\t\"S\n\013MsgNodeInfo\022\016\n" +
      "\006module\030\001 \001(\005\022\n\n\002id\030\002 \001(\003\022\014\n\004host\030\003 \001(\t\022" +
      "\014\n\004port\030\004 \001(\005\022\014\n\004bind\030\005 \001(\0052{\n\024ExamplePu" +
      "blicService\022;\n\005login\022\026.org.okraAx.v3.Msg" +
      "Auth\032\024.google.protobuf.Any\"\004\300>\341]\032&\300>\014\322>\035" +
      "org.okraAx.ExampleServiceImpl\310>\001B%\n\rorg." +
      "okraAx.v3B\022ExamplePublicProtoH\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
          org.okraAx.v3.AxOptions.getDescriptor(),
        }, assigner);
    internal_static_org_okraAx_v3_MsgAuth_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_okraAx_v3_MsgAuth_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_okraAx_v3_MsgAuth_descriptor,
        new java.lang.String[] { "Source", "Key", });
    internal_static_org_okraAx_v3_MsgNodeInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_okraAx_v3_MsgNodeInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_okraAx_v3_MsgNodeInfo_descriptor,
        new java.lang.String[] { "Module", "Id", "Host", "Port", "Bind", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(org.okraAx.v3.AxOptions.isPublic);
    registry.add(org.okraAx.v3.AxOptions.methodId);
    registry.add(org.okraAx.v3.AxOptions.serviceId);
    registry.add(org.okraAx.v3.AxOptions.serviceRef);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.AnyProto.getDescriptor();
    org.okraAx.v3.AxOptions.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
