// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Gpc.proto

package org.okraAx.v3;

public interface GpcVoidOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.okraAx.v3.GpcVoid)
    com.google.protobuf.MessageOrBuilder {
}
