// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoRoom.proto

package org.okraAx.v3;

public final class RoomProto {
  private RoomProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017ProtoRoom.proto\022\rorg.okraAx.v3\032(protoc" +
      "/include/google/protobuf/any.proto\032\017AxOp" +
      "tions.proto2\325\002\n\rAxRoomService\022?\n\013onEnter" +
      "Room\022\024.google.protobuf.Any\032\024.google.prot" +
      "obuf.Any\"\004\300>\371U\022>\n\nonExitRoom\022\024.google.pr" +
      "otobuf.Any\032\024.google.protobuf.Any\"\004\300>\372U\022A" +
      "\n\ronGetHallList\022\024.google.protobuf.Any\032\024." +
      "google.protobuf.Any\"\004\300>\373U\022?\n\013onRoomRoute" +
      "\022\024.google.protobuf.Any\032\024.google.protobuf" +
      ".Any\"\004\300>\374U\022:\n\006onChat\022\024.google.protobuf.A",
      "ny\032\024.google.protobuf.Any\"\004\300>\375U\032\003\300>\013B\034\n\ro" +
      "rg.okraAx.v3B\tRoomProtoH\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
          org.okraAx.v3.AxOptions.getDescriptor(),
        }, assigner);
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(org.okraAx.v3.AxOptions.methodId);
    registry.add(org.okraAx.v3.AxOptions.serviceId);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.AnyProto.getDescriptor();
    org.okraAx.v3.AxOptions.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
