// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AxRpcV3.proto

package org.okraAx.v3;

/**
 * <pre>
 *  RPC
 * </pre>
 *
 * Protobuf type {@code org.okraAx.v3.Rpc}
 */
public  final class Rpc extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.okraAx.v3.Rpc)
    RpcOrBuilder {
  // Use Rpc.newBuilder() to construct.
  private Rpc(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Rpc() {
    id_ = 0;
    api_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Rpc(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 16: {

            api_ = input.readInt32();
            break;
          }
          case 26: {
            org.okraAx.v3.AxAnyProto.AxAny.Builder subBuilder = null;
            if (data_ != null) {
              subBuilder = data_.toBuilder();
            }
            data_ = input.readMessage(org.okraAx.v3.AxAnyProto.AxAny.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(data_);
              data_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.okraAx.v3.AxRpc.internal_static_org_okraAx_v3_Rpc_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.okraAx.v3.AxRpc.internal_static_org_okraAx_v3_Rpc_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.okraAx.v3.Rpc.class, org.okraAx.v3.Rpc.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <pre>
   *  The unique request id.
   * </pre>
   *
   * <code>optional int32 id = 1;</code>
   */
  public int getId() {
    return id_;
  }

  public static final int API_FIELD_NUMBER = 2;
  private int api_;
  /**
   * <pre>
   *    调用的服务接口id
   * </pre>
   *
   * <code>optional int32 api = 2;</code>
   */
  public int getApi() {
    return api_;
  }

  public static final int DATA_FIELD_NUMBER = 3;
  private org.okraAx.v3.AxAnyProto.AxAny data_;
  /**
   * <pre>
   *  请求参数. 允许任意pb类型的message成为参数
   * </pre>
   *
   * <code>optional .org.okraAx.v3.AxAny data = 3;</code>
   */
  public boolean hasData() {
    return data_ != null;
  }
  /**
   * <pre>
   *  请求参数. 允许任意pb类型的message成为参数
   * </pre>
   *
   * <code>optional .org.okraAx.v3.AxAny data = 3;</code>
   */
  public org.okraAx.v3.AxAnyProto.AxAny getData() {
    return data_ == null ? org.okraAx.v3.AxAnyProto.AxAny.getDefaultInstance() : data_;
  }
  /**
   * <pre>
   *  请求参数. 允许任意pb类型的message成为参数
   * </pre>
   *
   * <code>optional .org.okraAx.v3.AxAny data = 3;</code>
   */
  public org.okraAx.v3.AxAnyProto.AxAnyOrBuilder getDataOrBuilder() {
    return getData();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (api_ != 0) {
      output.writeInt32(2, api_);
    }
    if (data_ != null) {
      output.writeMessage(3, getData());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (api_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, api_);
    }
    if (data_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getData());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.okraAx.v3.Rpc)) {
      return super.equals(obj);
    }
    org.okraAx.v3.Rpc other = (org.okraAx.v3.Rpc) obj;

    boolean result = true;
    result = result && (getId()
        == other.getId());
    result = result && (getApi()
        == other.getApi());
    result = result && (hasData() == other.hasData());
    if (hasData()) {
      result = result && getData()
          .equals(other.getData());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + API_FIELD_NUMBER;
    hash = (53 * hash) + getApi();
    if (hasData()) {
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.okraAx.v3.Rpc parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.okraAx.v3.Rpc parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.okraAx.v3.Rpc parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.okraAx.v3.Rpc parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.okraAx.v3.Rpc parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.okraAx.v3.Rpc parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.okraAx.v3.Rpc parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.okraAx.v3.Rpc parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.okraAx.v3.Rpc parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.okraAx.v3.Rpc parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.okraAx.v3.Rpc prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *  RPC
   * </pre>
   *
   * Protobuf type {@code org.okraAx.v3.Rpc}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.okraAx.v3.Rpc)
      org.okraAx.v3.RpcOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.okraAx.v3.AxRpc.internal_static_org_okraAx_v3_Rpc_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.okraAx.v3.AxRpc.internal_static_org_okraAx_v3_Rpc_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.okraAx.v3.Rpc.class, org.okraAx.v3.Rpc.Builder.class);
    }

    // Construct using org.okraAx.v3.Rpc.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      id_ = 0;

      api_ = 0;

      if (dataBuilder_ == null) {
        data_ = null;
      } else {
        data_ = null;
        dataBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.okraAx.v3.AxRpc.internal_static_org_okraAx_v3_Rpc_descriptor;
    }

    public org.okraAx.v3.Rpc getDefaultInstanceForType() {
      return org.okraAx.v3.Rpc.getDefaultInstance();
    }

    public org.okraAx.v3.Rpc build() {
      org.okraAx.v3.Rpc result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.okraAx.v3.Rpc buildPartial() {
      org.okraAx.v3.Rpc result = new org.okraAx.v3.Rpc(this);
      result.id_ = id_;
      result.api_ = api_;
      if (dataBuilder_ == null) {
        result.data_ = data_;
      } else {
        result.data_ = dataBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.okraAx.v3.Rpc) {
        return mergeFrom((org.okraAx.v3.Rpc)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.okraAx.v3.Rpc other) {
      if (other == org.okraAx.v3.Rpc.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (other.getApi() != 0) {
        setApi(other.getApi());
      }
      if (other.hasData()) {
        mergeData(other.getData());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.okraAx.v3.Rpc parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.okraAx.v3.Rpc) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int id_ ;
    /**
     * <pre>
     *  The unique request id.
     * </pre>
     *
     * <code>optional int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }
    /**
     * <pre>
     *  The unique request id.
     * </pre>
     *
     * <code>optional int32 id = 1;</code>
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *  The unique request id.
     * </pre>
     *
     * <code>optional int32 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private int api_ ;
    /**
     * <pre>
     *    调用的服务接口id
     * </pre>
     *
     * <code>optional int32 api = 2;</code>
     */
    public int getApi() {
      return api_;
    }
    /**
     * <pre>
     *    调用的服务接口id
     * </pre>
     *
     * <code>optional int32 api = 2;</code>
     */
    public Builder setApi(int value) {
      
      api_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *    调用的服务接口id
     * </pre>
     *
     * <code>optional int32 api = 2;</code>
     */
    public Builder clearApi() {
      
      api_ = 0;
      onChanged();
      return this;
    }

    private org.okraAx.v3.AxAnyProto.AxAny data_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.okraAx.v3.AxAnyProto.AxAny, org.okraAx.v3.AxAnyProto.AxAny.Builder, org.okraAx.v3.AxAnyProto.AxAnyOrBuilder> dataBuilder_;
    /**
     * <pre>
     *  请求参数. 允许任意pb类型的message成为参数
     * </pre>
     *
     * <code>optional .org.okraAx.v3.AxAny data = 3;</code>
     */
    public boolean hasData() {
      return dataBuilder_ != null || data_ != null;
    }
    /**
     * <pre>
     *  请求参数. 允许任意pb类型的message成为参数
     * </pre>
     *
     * <code>optional .org.okraAx.v3.AxAny data = 3;</code>
     */
    public org.okraAx.v3.AxAnyProto.AxAny getData() {
      if (dataBuilder_ == null) {
        return data_ == null ? org.okraAx.v3.AxAnyProto.AxAny.getDefaultInstance() : data_;
      } else {
        return dataBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *  请求参数. 允许任意pb类型的message成为参数
     * </pre>
     *
     * <code>optional .org.okraAx.v3.AxAny data = 3;</code>
     */
    public Builder setData(org.okraAx.v3.AxAnyProto.AxAny value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        dataBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *  请求参数. 允许任意pb类型的message成为参数
     * </pre>
     *
     * <code>optional .org.okraAx.v3.AxAny data = 3;</code>
     */
    public Builder setData(
        org.okraAx.v3.AxAnyProto.AxAny.Builder builderForValue) {
      if (dataBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        dataBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *  请求参数. 允许任意pb类型的message成为参数
     * </pre>
     *
     * <code>optional .org.okraAx.v3.AxAny data = 3;</code>
     */
    public Builder mergeData(org.okraAx.v3.AxAnyProto.AxAny value) {
      if (dataBuilder_ == null) {
        if (data_ != null) {
          data_ =
            org.okraAx.v3.AxAnyProto.AxAny.newBuilder(data_).mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        dataBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *  请求参数. 允许任意pb类型的message成为参数
     * </pre>
     *
     * <code>optional .org.okraAx.v3.AxAny data = 3;</code>
     */
    public Builder clearData() {
      if (dataBuilder_ == null) {
        data_ = null;
        onChanged();
      } else {
        data_ = null;
        dataBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *  请求参数. 允许任意pb类型的message成为参数
     * </pre>
     *
     * <code>optional .org.okraAx.v3.AxAny data = 3;</code>
     */
    public org.okraAx.v3.AxAnyProto.AxAny.Builder getDataBuilder() {
      
      onChanged();
      return getDataFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *  请求参数. 允许任意pb类型的message成为参数
     * </pre>
     *
     * <code>optional .org.okraAx.v3.AxAny data = 3;</code>
     */
    public org.okraAx.v3.AxAnyProto.AxAnyOrBuilder getDataOrBuilder() {
      if (dataBuilder_ != null) {
        return dataBuilder_.getMessageOrBuilder();
      } else {
        return data_ == null ?
            org.okraAx.v3.AxAnyProto.AxAny.getDefaultInstance() : data_;
      }
    }
    /**
     * <pre>
     *  请求参数. 允许任意pb类型的message成为参数
     * </pre>
     *
     * <code>optional .org.okraAx.v3.AxAny data = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.okraAx.v3.AxAnyProto.AxAny, org.okraAx.v3.AxAnyProto.AxAny.Builder, org.okraAx.v3.AxAnyProto.AxAnyOrBuilder> 
        getDataFieldBuilder() {
      if (dataBuilder_ == null) {
        dataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.okraAx.v3.AxAnyProto.AxAny, org.okraAx.v3.AxAnyProto.AxAny.Builder, org.okraAx.v3.AxAnyProto.AxAnyOrBuilder>(
                getData(),
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      return dataBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:org.okraAx.v3.Rpc)
  }

  // @@protoc_insertion_point(class_scope:org.okraAx.v3.Rpc)
  private static final org.okraAx.v3.Rpc DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.okraAx.v3.Rpc();
  }

  public static org.okraAx.v3.Rpc getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Rpc>
      PARSER = new com.google.protobuf.AbstractParser<Rpc>() {
    public Rpc parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Rpc(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Rpc> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Rpc> getParserForType() {
    return PARSER;
  }

  public org.okraAx.v3.Rpc getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

