// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AxRpcV3.proto

package org.okraAx.v3;

public interface RpcErrorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.okraAx.v3.RpcError)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * error code
   * </pre>
   *
   * <code>optional int32 state = 1;</code>
   */
  int getState();

  /**
   * <pre>
   * response special error message. [Nullable].
   * </pre>
   *
   * <code>optional string msg = 2;</code>
   */
  java.lang.String getMsg();
  /**
   * <pre>
   * response special error message. [Nullable].
   * </pre>
   *
   * <code>optional string msg = 2;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
