// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AxRpcV3.proto

package org.okraAx.v3;

public interface RpcVoidOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.okraAx.v3.RpcVoid)
    com.google.protobuf.MessageOrBuilder {
}
