// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BeanRelay.proto

package org.okraAx.v3.beans;

public final class GpcBnRelay {
  private GpcBnRelay() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_okraAx_v3_RpcOnRelay_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_okraAx_v3_RpcOnRelay_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017BeanRelay.proto\022\rorg.okraAx.v3\032\tGpc.pr" +
      "oto\"B\n\nRpcOnRelay\022\016\n\006target\030\001 \001(\003\022$\n\004cal" +
      "l\030\002 \001(\0132\026.org.okraAx.v3.GpcCallB%\n\023org.o" +
      "kraAx.v3.beansB\nGpcBnRelayH\001P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.okraAx.v3.Gpc.getDescriptor(),
        }, assigner);
    internal_static_org_okraAx_v3_RpcOnRelay_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_okraAx_v3_RpcOnRelay_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_okraAx_v3_RpcOnRelay_descriptor,
        new java.lang.String[] { "Target", "Call", });
    org.okraAx.v3.Gpc.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
