// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BeanRelay.proto

package org.okraAx.v3.beans;

public interface RpcOnRelayOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.okraAx.v3.RpcOnRelay)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 target = 1;</code>
   */
  long getTarget();

  /**
   * <code>optional .org.okraAx.v3.GpcCall call = 2;</code>
   */
  boolean hasCall();
  /**
   * <code>optional .org.okraAx.v3.GpcCall call = 2;</code>
   */
  org.okraAx.v3.GpcCall getCall();
  /**
   * <code>optional .org.okraAx.v3.GpcCall call = 2;</code>
   */
  org.okraAx.v3.GpcCallOrBuilder getCallOrBuilder();
}
