// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BeanCommon.proto

package org.okraAx.v3.beans.common;

public final class GpcBnCommon {
  private GpcBnCommon() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_okraAx_v3_UserInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_okraAx_v3_UserInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_okraAx_v3_LogServerInfoBean_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_okraAx_v3_LogServerInfoBean_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_okraAx_v3_ReportClientLogBean_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_okraAx_v3_ReportClientLogBean_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_okraAx_v3_ClientLogMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_okraAx_v3_ClientLogMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_okraAx_v3_ClientLogMessage_ContextEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_okraAx_v3_ClientLogMessage_ContextEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020BeanCommon.proto\022\rorg.okraAx.v3\032\013AxAny" +
      ".proto\"X\n\010UserInfo\022\013\n\003uid\030\001 \001(\003\022\014\n\004name\030" +
      "\002 \001(\t\022\016\n\006figure\030\003 \001(\005\022!\n\003ext\030\004 \001(\0132\024.org" +
      ".okraAx.v3.AxAny\" \n\021LogServerInfoBean\022\013\n" +
      "\003url\030\001 \001(\t\"D\n\023ReportClientLogBean\022-\n\004lis" +
      "t\030\001 \003(\0132\037.org.okraAx.v3.ClientLogMessage" +
      "\"\267\001\n\020ClientLogMessage\022=\n\007context\030\001 \003(\0132," +
      ".org.okraAx.v3.ClientLogMessage.ContextE" +
      "ntry\022\020\n\010logLevel\030\002 \001(\005\022\017\n\007message\030\003 \001(\t\022" +
      "\021\n\tthrowable\030\004 \001(\t\032.\n\014ContextEntry\022\013\n\003ke",
      "y\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001B-\n\032org.okraAx" +
      ".v3.beans.commonB\013GpcBnCommonH\001P\001b\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.okraAx.v3.AxAnyProto.getDescriptor(),
        }, assigner);
    internal_static_org_okraAx_v3_UserInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_okraAx_v3_UserInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_okraAx_v3_UserInfo_descriptor,
        new java.lang.String[] { "Uid", "Name", "Figure", "Ext", });
    internal_static_org_okraAx_v3_LogServerInfoBean_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_okraAx_v3_LogServerInfoBean_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_okraAx_v3_LogServerInfoBean_descriptor,
        new java.lang.String[] { "Url", });
    internal_static_org_okraAx_v3_ReportClientLogBean_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_okraAx_v3_ReportClientLogBean_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_okraAx_v3_ReportClientLogBean_descriptor,
        new java.lang.String[] { "List", });
    internal_static_org_okraAx_v3_ClientLogMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_org_okraAx_v3_ClientLogMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_okraAx_v3_ClientLogMessage_descriptor,
        new java.lang.String[] { "Context", "LogLevel", "Message", "Throwable", });
    internal_static_org_okraAx_v3_ClientLogMessage_ContextEntry_descriptor =
      internal_static_org_okraAx_v3_ClientLogMessage_descriptor.getNestedTypes().get(0);
    internal_static_org_okraAx_v3_ClientLogMessage_ContextEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_okraAx_v3_ClientLogMessage_ContextEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    org.okraAx.v3.AxAnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
