// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BeanCommon.proto

package org.okraAx.v3.beans.common;

public interface InfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.okraAx.v3.Info)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string version = 1;</code>
   */
  java.lang.String getVersion();
  /**
   * <code>optional string version = 1;</code>
   */
  com.google.protobuf.ByteString
      getVersionBytes();
}
