// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BeanCommon.proto

package org.okraAx.v3.beans.common;

public interface ReportClientLogBeanOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.okraAx.v3.ReportClientLogBean)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .org.okraAx.v3.ClientLogMessage list = 1;</code>
   */
  java.util.List<org.okraAx.v3.beans.common.ClientLogMessage> 
      getListList();
  /**
   * <code>repeated .org.okraAx.v3.ClientLogMessage list = 1;</code>
   */
  org.okraAx.v3.beans.common.ClientLogMessage getList(int index);
  /**
   * <code>repeated .org.okraAx.v3.ClientLogMessage list = 1;</code>
   */
  int getListCount();
  /**
   * <code>repeated .org.okraAx.v3.ClientLogMessage list = 1;</code>
   */
  java.util.List<? extends org.okraAx.v3.beans.common.ClientLogMessageOrBuilder> 
      getListOrBuilderList();
  /**
   * <code>repeated .org.okraAx.v3.ClientLogMessage list = 1;</code>
   */
  org.okraAx.v3.beans.common.ClientLogMessageOrBuilder getListOrBuilder(
      int index);
}
