// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BeanCommon.proto

package org.okraAx.v3.beans.common;

/**
 * <pre>
 *   用户信息
 * </pre>
 *
 * Protobuf type {@code org.okraAx.v3.UserInfo}
 */
public  final class UserInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.okraAx.v3.UserInfo)
    UserInfoOrBuilder {
  // Use UserInfo.newBuilder() to construct.
  private UserInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UserInfo() {
    uid_ = 0L;
    name_ = "";
    figure_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private UserInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            uid_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 24: {

            figure_ = input.readInt32();
            break;
          }
          case 34: {
            org.okraAx.v3.AxAnyProto.AxAny.Builder subBuilder = null;
            if (ext_ != null) {
              subBuilder = ext_.toBuilder();
            }
            ext_ = input.readMessage(org.okraAx.v3.AxAnyProto.AxAny.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(ext_);
              ext_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.okraAx.v3.beans.common.GpcBnCommon.internal_static_org_okraAx_v3_UserInfo_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.okraAx.v3.beans.common.GpcBnCommon.internal_static_org_okraAx_v3_UserInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.okraAx.v3.beans.common.UserInfo.class, org.okraAx.v3.beans.common.UserInfo.Builder.class);
  }

  public static final int UID_FIELD_NUMBER = 1;
  private long uid_;
  /**
   * <pre>
   *  角色 唯一ID
   * </pre>
   *
   * <code>optional int64 uid = 1;</code>
   */
  public long getUid() {
    return uid_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <pre>
   *  角色名称
   * </pre>
   *
   * <code>optional string name = 2;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *  角色名称
   * </pre>
   *
   * <code>optional string name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FIGURE_FIELD_NUMBER = 3;
  private int figure_;
  /**
   * <pre>
   *  形象
   * </pre>
   *
   * <code>optional int32 figure = 3;</code>
   */
  public int getFigure() {
    return figure_;
  }

  public static final int EXT_FIELD_NUMBER = 4;
  private org.okraAx.v3.AxAnyProto.AxAny ext_;
  /**
   * <pre>
   *  扩展数据 - 战绩等等
   * </pre>
   *
   * <code>optional .org.okraAx.v3.AxAny ext = 4;</code>
   */
  public boolean hasExt() {
    return ext_ != null;
  }
  /**
   * <pre>
   *  扩展数据 - 战绩等等
   * </pre>
   *
   * <code>optional .org.okraAx.v3.AxAny ext = 4;</code>
   */
  public org.okraAx.v3.AxAnyProto.AxAny getExt() {
    return ext_ == null ? org.okraAx.v3.AxAnyProto.AxAny.getDefaultInstance() : ext_;
  }
  /**
   * <pre>
   *  扩展数据 - 战绩等等
   * </pre>
   *
   * <code>optional .org.okraAx.v3.AxAny ext = 4;</code>
   */
  public org.okraAx.v3.AxAnyProto.AxAnyOrBuilder getExtOrBuilder() {
    return getExt();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (uid_ != 0L) {
      output.writeInt64(1, uid_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (figure_ != 0) {
      output.writeInt32(3, figure_);
    }
    if (ext_ != null) {
      output.writeMessage(4, getExt());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (uid_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, uid_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (figure_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, figure_);
    }
    if (ext_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getExt());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.okraAx.v3.beans.common.UserInfo)) {
      return super.equals(obj);
    }
    org.okraAx.v3.beans.common.UserInfo other = (org.okraAx.v3.beans.common.UserInfo) obj;

    boolean result = true;
    result = result && (getUid()
        == other.getUid());
    result = result && getName()
        .equals(other.getName());
    result = result && (getFigure()
        == other.getFigure());
    result = result && (hasExt() == other.hasExt());
    if (hasExt()) {
      result = result && getExt()
          .equals(other.getExt());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + UID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUid());
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + FIGURE_FIELD_NUMBER;
    hash = (53 * hash) + getFigure();
    if (hasExt()) {
      hash = (37 * hash) + EXT_FIELD_NUMBER;
      hash = (53 * hash) + getExt().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.okraAx.v3.beans.common.UserInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.okraAx.v3.beans.common.UserInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.okraAx.v3.beans.common.UserInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.okraAx.v3.beans.common.UserInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.okraAx.v3.beans.common.UserInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.okraAx.v3.beans.common.UserInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.okraAx.v3.beans.common.UserInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.okraAx.v3.beans.common.UserInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.okraAx.v3.beans.common.UserInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.okraAx.v3.beans.common.UserInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.okraAx.v3.beans.common.UserInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *   用户信息
   * </pre>
   *
   * Protobuf type {@code org.okraAx.v3.UserInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.okraAx.v3.UserInfo)
      org.okraAx.v3.beans.common.UserInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.okraAx.v3.beans.common.GpcBnCommon.internal_static_org_okraAx_v3_UserInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.okraAx.v3.beans.common.GpcBnCommon.internal_static_org_okraAx_v3_UserInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.okraAx.v3.beans.common.UserInfo.class, org.okraAx.v3.beans.common.UserInfo.Builder.class);
    }

    // Construct using org.okraAx.v3.beans.common.UserInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      uid_ = 0L;

      name_ = "";

      figure_ = 0;

      if (extBuilder_ == null) {
        ext_ = null;
      } else {
        ext_ = null;
        extBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.okraAx.v3.beans.common.GpcBnCommon.internal_static_org_okraAx_v3_UserInfo_descriptor;
    }

    public org.okraAx.v3.beans.common.UserInfo getDefaultInstanceForType() {
      return org.okraAx.v3.beans.common.UserInfo.getDefaultInstance();
    }

    public org.okraAx.v3.beans.common.UserInfo build() {
      org.okraAx.v3.beans.common.UserInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.okraAx.v3.beans.common.UserInfo buildPartial() {
      org.okraAx.v3.beans.common.UserInfo result = new org.okraAx.v3.beans.common.UserInfo(this);
      result.uid_ = uid_;
      result.name_ = name_;
      result.figure_ = figure_;
      if (extBuilder_ == null) {
        result.ext_ = ext_;
      } else {
        result.ext_ = extBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.okraAx.v3.beans.common.UserInfo) {
        return mergeFrom((org.okraAx.v3.beans.common.UserInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.okraAx.v3.beans.common.UserInfo other) {
      if (other == org.okraAx.v3.beans.common.UserInfo.getDefaultInstance()) return this;
      if (other.getUid() != 0L) {
        setUid(other.getUid());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.getFigure() != 0) {
        setFigure(other.getFigure());
      }
      if (other.hasExt()) {
        mergeExt(other.getExt());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.okraAx.v3.beans.common.UserInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.okraAx.v3.beans.common.UserInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long uid_ ;
    /**
     * <pre>
     *  角色 唯一ID
     * </pre>
     *
     * <code>optional int64 uid = 1;</code>
     */
    public long getUid() {
      return uid_;
    }
    /**
     * <pre>
     *  角色 唯一ID
     * </pre>
     *
     * <code>optional int64 uid = 1;</code>
     */
    public Builder setUid(long value) {
      
      uid_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *  角色 唯一ID
     * </pre>
     *
     * <code>optional int64 uid = 1;</code>
     */
    public Builder clearUid() {
      
      uid_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     *  角色名称
     * </pre>
     *
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *  角色名称
     * </pre>
     *
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *  角色名称
     * </pre>
     *
     * <code>optional string name = 2;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *  角色名称
     * </pre>
     *
     * <code>optional string name = 2;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *  角色名称
     * </pre>
     *
     * <code>optional string name = 2;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private int figure_ ;
    /**
     * <pre>
     *  形象
     * </pre>
     *
     * <code>optional int32 figure = 3;</code>
     */
    public int getFigure() {
      return figure_;
    }
    /**
     * <pre>
     *  形象
     * </pre>
     *
     * <code>optional int32 figure = 3;</code>
     */
    public Builder setFigure(int value) {
      
      figure_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *  形象
     * </pre>
     *
     * <code>optional int32 figure = 3;</code>
     */
    public Builder clearFigure() {
      
      figure_ = 0;
      onChanged();
      return this;
    }

    private org.okraAx.v3.AxAnyProto.AxAny ext_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.okraAx.v3.AxAnyProto.AxAny, org.okraAx.v3.AxAnyProto.AxAny.Builder, org.okraAx.v3.AxAnyProto.AxAnyOrBuilder> extBuilder_;
    /**
     * <pre>
     *  扩展数据 - 战绩等等
     * </pre>
     *
     * <code>optional .org.okraAx.v3.AxAny ext = 4;</code>
     */
    public boolean hasExt() {
      return extBuilder_ != null || ext_ != null;
    }
    /**
     * <pre>
     *  扩展数据 - 战绩等等
     * </pre>
     *
     * <code>optional .org.okraAx.v3.AxAny ext = 4;</code>
     */
    public org.okraAx.v3.AxAnyProto.AxAny getExt() {
      if (extBuilder_ == null) {
        return ext_ == null ? org.okraAx.v3.AxAnyProto.AxAny.getDefaultInstance() : ext_;
      } else {
        return extBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *  扩展数据 - 战绩等等
     * </pre>
     *
     * <code>optional .org.okraAx.v3.AxAny ext = 4;</code>
     */
    public Builder setExt(org.okraAx.v3.AxAnyProto.AxAny value) {
      if (extBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ext_ = value;
        onChanged();
      } else {
        extBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *  扩展数据 - 战绩等等
     * </pre>
     *
     * <code>optional .org.okraAx.v3.AxAny ext = 4;</code>
     */
    public Builder setExt(
        org.okraAx.v3.AxAnyProto.AxAny.Builder builderForValue) {
      if (extBuilder_ == null) {
        ext_ = builderForValue.build();
        onChanged();
      } else {
        extBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *  扩展数据 - 战绩等等
     * </pre>
     *
     * <code>optional .org.okraAx.v3.AxAny ext = 4;</code>
     */
    public Builder mergeExt(org.okraAx.v3.AxAnyProto.AxAny value) {
      if (extBuilder_ == null) {
        if (ext_ != null) {
          ext_ =
            org.okraAx.v3.AxAnyProto.AxAny.newBuilder(ext_).mergeFrom(value).buildPartial();
        } else {
          ext_ = value;
        }
        onChanged();
      } else {
        extBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *  扩展数据 - 战绩等等
     * </pre>
     *
     * <code>optional .org.okraAx.v3.AxAny ext = 4;</code>
     */
    public Builder clearExt() {
      if (extBuilder_ == null) {
        ext_ = null;
        onChanged();
      } else {
        ext_ = null;
        extBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *  扩展数据 - 战绩等等
     * </pre>
     *
     * <code>optional .org.okraAx.v3.AxAny ext = 4;</code>
     */
    public org.okraAx.v3.AxAnyProto.AxAny.Builder getExtBuilder() {
      
      onChanged();
      return getExtFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *  扩展数据 - 战绩等等
     * </pre>
     *
     * <code>optional .org.okraAx.v3.AxAny ext = 4;</code>
     */
    public org.okraAx.v3.AxAnyProto.AxAnyOrBuilder getExtOrBuilder() {
      if (extBuilder_ != null) {
        return extBuilder_.getMessageOrBuilder();
      } else {
        return ext_ == null ?
            org.okraAx.v3.AxAnyProto.AxAny.getDefaultInstance() : ext_;
      }
    }
    /**
     * <pre>
     *  扩展数据 - 战绩等等
     * </pre>
     *
     * <code>optional .org.okraAx.v3.AxAny ext = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.okraAx.v3.AxAnyProto.AxAny, org.okraAx.v3.AxAnyProto.AxAny.Builder, org.okraAx.v3.AxAnyProto.AxAnyOrBuilder> 
        getExtFieldBuilder() {
      if (extBuilder_ == null) {
        extBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.okraAx.v3.AxAnyProto.AxAny, org.okraAx.v3.AxAnyProto.AxAny.Builder, org.okraAx.v3.AxAnyProto.AxAnyOrBuilder>(
                getExt(),
                getParentForChildren(),
                isClean());
        ext_ = null;
      }
      return extBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:org.okraAx.v3.UserInfo)
  }

  // @@protoc_insertion_point(class_scope:org.okraAx.v3.UserInfo)
  private static final org.okraAx.v3.beans.common.UserInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.okraAx.v3.beans.common.UserInfo();
  }

  public static org.okraAx.v3.beans.common.UserInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserInfo>
      PARSER = new com.google.protobuf.AbstractParser<UserInfo>() {
    public UserInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UserInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UserInfo> getParserForType() {
    return PARSER;
  }

  public org.okraAx.v3.beans.common.UserInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

