// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BeanCommon.proto

package org.okraAx.v3.beans.common;

public interface UserInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.okraAx.v3.UserInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *  角色 唯一ID
   * </pre>
   *
   * <code>optional int64 uid = 1;</code>
   */
  long getUid();

  /**
   * <pre>
   *  角色名称
   * </pre>
   *
   * <code>optional string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   *  角色名称
   * </pre>
   *
   * <code>optional string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   *  形象
   * </pre>
   *
   * <code>optional int32 figure = 3;</code>
   */
  int getFigure();

  /**
   * <pre>
   *  扩展数据 - 战绩等等
   * </pre>
   *
   * <code>optional .org.okraAx.v3.AxAny ext = 4;</code>
   */
  boolean hasExt();
  /**
   * <pre>
   *  扩展数据 - 战绩等等
   * </pre>
   *
   * <code>optional .org.okraAx.v3.AxAny ext = 4;</code>
   */
  org.okraAx.v3.AxAnyProto.AxAny getExt();
  /**
   * <pre>
   *  扩展数据 - 战绩等等
   * </pre>
   *
   * <code>optional .org.okraAx.v3.AxAny ext = 4;</code>
   */
  org.okraAx.v3.AxAnyProto.AxAnyOrBuilder getExtOrBuilder();
}
