// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BeanRoomPub.proto

package org.okraAx.v3.beans.roomPub;

public interface ApiOnMoveChessOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.okraAx.v3.ApiOnMoveChess)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 fromX = 1;</code>
   */
  int getFromX();

  /**
   * <code>optional int32 fromY = 2;</code>
   */
  int getFromY();

  /**
   * <code>optional int32 toX = 3;</code>
   */
  int getToX();

  /**
   * <code>optional int32 toY = 4;</code>
   */
  int getToY();
}
