// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BeanRoomPub.proto

package org.okraAx.v3.beans.roomPub;

public interface ApiOnPlayerConnectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.okraAx.v3.ApiOnPlayerConnect)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *  角色唯一ID
   * </pre>
   *
   * <code>optional int64 uid = 1;</code>
   */
  long getUid();

  /**
   * <pre>
   *  秘钥
   * </pre>
   *
   * <code>optional int64 security = 2;</code>
   */
  long getSecurity();
}
