// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BeanRoomPub.proto

package org.okraAx.v3.beans.roomPub;

public interface ApiOnEnterRoomOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.okraAx.v3.ApiOnEnterRoom)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 roomId = 1;</code>
   */
  int getRoomId();

  /**
   * <code>optional int32 seat = 2;</code>
   */
  int getSeat();

  /**
   * <code>optional int64 uid = 3;</code>
   */
  long getUid();

  /**
   * <code>optional string name = 4;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 4;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
