// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BeanRoomPub.proto

package org.okraAx.v3.beans.roomPub;

public interface ApiOnChatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.okraAx.v3.ApiOnChat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .org.okraAx.v3.MsgOnChat chat = 1;</code>
   */
  boolean hasChat();
  /**
   * <code>optional .org.okraAx.v3.MsgOnChat chat = 1;</code>
   */
  org.okraAx.v3.beans.roomPub.MsgOnChat getChat();
  /**
   * <code>optional .org.okraAx.v3.MsgOnChat chat = 1;</code>
   */
  org.okraAx.v3.beans.roomPub.MsgOnChatOrBuilder getChatOrBuilder();
}
