// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BeanRoomPub.proto

package org.okraAx.v3.beans.roomPub;

/**
 * Protobuf type {@code org.okraAx.v3.ApiOnGetReady}
 */
public  final class ApiOnGetReady extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.okraAx.v3.ApiOnGetReady)
    ApiOnGetReadyOrBuilder {
  // Use ApiOnGetReady.newBuilder() to construct.
  private ApiOnGetReady(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ApiOnGetReady() {
    ready_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ApiOnGetReady(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            ready_ = input.readBool();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.okraAx.v3.beans.roomPub.GpcBnRoomPub.internal_static_org_okraAx_v3_ApiOnGetReady_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.okraAx.v3.beans.roomPub.GpcBnRoomPub.internal_static_org_okraAx_v3_ApiOnGetReady_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.okraAx.v3.beans.roomPub.ApiOnGetReady.class, org.okraAx.v3.beans.roomPub.ApiOnGetReady.Builder.class);
  }

  public static final int READY_FIELD_NUMBER = 1;
  private boolean ready_;
  /**
   * <code>optional bool ready = 1;</code>
   */
  public boolean getReady() {
    return ready_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (ready_ != false) {
      output.writeBool(1, ready_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (ready_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, ready_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.okraAx.v3.beans.roomPub.ApiOnGetReady)) {
      return super.equals(obj);
    }
    org.okraAx.v3.beans.roomPub.ApiOnGetReady other = (org.okraAx.v3.beans.roomPub.ApiOnGetReady) obj;

    boolean result = true;
    result = result && (getReady()
        == other.getReady());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + READY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getReady());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.okraAx.v3.beans.roomPub.ApiOnGetReady parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.okraAx.v3.beans.roomPub.ApiOnGetReady parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.okraAx.v3.beans.roomPub.ApiOnGetReady parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.okraAx.v3.beans.roomPub.ApiOnGetReady parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.okraAx.v3.beans.roomPub.ApiOnGetReady parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.okraAx.v3.beans.roomPub.ApiOnGetReady parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.okraAx.v3.beans.roomPub.ApiOnGetReady parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.okraAx.v3.beans.roomPub.ApiOnGetReady parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.okraAx.v3.beans.roomPub.ApiOnGetReady parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.okraAx.v3.beans.roomPub.ApiOnGetReady parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.okraAx.v3.beans.roomPub.ApiOnGetReady prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.okraAx.v3.ApiOnGetReady}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.okraAx.v3.ApiOnGetReady)
      org.okraAx.v3.beans.roomPub.ApiOnGetReadyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.okraAx.v3.beans.roomPub.GpcBnRoomPub.internal_static_org_okraAx_v3_ApiOnGetReady_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.okraAx.v3.beans.roomPub.GpcBnRoomPub.internal_static_org_okraAx_v3_ApiOnGetReady_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.okraAx.v3.beans.roomPub.ApiOnGetReady.class, org.okraAx.v3.beans.roomPub.ApiOnGetReady.Builder.class);
    }

    // Construct using org.okraAx.v3.beans.roomPub.ApiOnGetReady.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      ready_ = false;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.okraAx.v3.beans.roomPub.GpcBnRoomPub.internal_static_org_okraAx_v3_ApiOnGetReady_descriptor;
    }

    public org.okraAx.v3.beans.roomPub.ApiOnGetReady getDefaultInstanceForType() {
      return org.okraAx.v3.beans.roomPub.ApiOnGetReady.getDefaultInstance();
    }

    public org.okraAx.v3.beans.roomPub.ApiOnGetReady build() {
      org.okraAx.v3.beans.roomPub.ApiOnGetReady result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.okraAx.v3.beans.roomPub.ApiOnGetReady buildPartial() {
      org.okraAx.v3.beans.roomPub.ApiOnGetReady result = new org.okraAx.v3.beans.roomPub.ApiOnGetReady(this);
      result.ready_ = ready_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.okraAx.v3.beans.roomPub.ApiOnGetReady) {
        return mergeFrom((org.okraAx.v3.beans.roomPub.ApiOnGetReady)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.okraAx.v3.beans.roomPub.ApiOnGetReady other) {
      if (other == org.okraAx.v3.beans.roomPub.ApiOnGetReady.getDefaultInstance()) return this;
      if (other.getReady() != false) {
        setReady(other.getReady());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.okraAx.v3.beans.roomPub.ApiOnGetReady parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.okraAx.v3.beans.roomPub.ApiOnGetReady) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean ready_ ;
    /**
     * <code>optional bool ready = 1;</code>
     */
    public boolean getReady() {
      return ready_;
    }
    /**
     * <code>optional bool ready = 1;</code>
     */
    public Builder setReady(boolean value) {
      
      ready_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool ready = 1;</code>
     */
    public Builder clearReady() {
      
      ready_ = false;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:org.okraAx.v3.ApiOnGetReady)
  }

  // @@protoc_insertion_point(class_scope:org.okraAx.v3.ApiOnGetReady)
  private static final org.okraAx.v3.beans.roomPub.ApiOnGetReady DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.okraAx.v3.beans.roomPub.ApiOnGetReady();
  }

  public static org.okraAx.v3.beans.roomPub.ApiOnGetReady getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ApiOnGetReady>
      PARSER = new com.google.protobuf.AbstractParser<ApiOnGetReady>() {
    public ApiOnGetReady parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ApiOnGetReady(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ApiOnGetReady> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ApiOnGetReady> getParserForType() {
    return PARSER;
  }

  public org.okraAx.v3.beans.roomPub.ApiOnGetReady getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

