// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BeanPlayerRoom.proto

package org.okraAx.v3.beans.roomPub;

public final class GpcBnPlayerRoom {
  private GpcBnPlayerRoom() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_okraAx_v3_PmOnEnterRoom_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_okraAx_v3_PmOnEnterRoom_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_okraAx_v3_PmOnExitRoom_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_okraAx_v3_PmOnExitRoom_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_okraAx_v3_PmOnChat_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_okraAx_v3_PmOnChat_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024BeanPlayerRoom.proto\022\rorg.okraAx.v3\032\013A" +
      "xAny.proto\".\n\rPmOnEnterRoom\022\016\n\006roomId\030\001 " +
      "\001(\003\022\r\n\005index\030\002 \001(\005\"\036\n\014PmOnExitRoom\022\016\n\006ro" +
      "omId\030\001 \001(\003\"x\n\010PmOnChat\022\017\n\007channel\030\001 \001(\005\022" +
      "\016\n\006roomId\030\002 \001(\003\022\017\n\007message\030\003 \001(\t\022\014\n\004from" +
      "\030\004 \001(\003\022\020\n\010fromName\030\005 \001(\t\022\n\n\002to\030\006 \001(\003\022\016\n\006" +
      "toName\030\007 \001(\tBG\n\033org.okraAx.v3.beans.room" +
      "PubB\017GpcBnPlayerRoomH\001P\001\252\002\022Okra.Gpb.Gene" +
      "ratedb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.okraAx.v3.AxAnyProto.getDescriptor(),
        }, assigner);
    internal_static_org_okraAx_v3_PmOnEnterRoom_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_okraAx_v3_PmOnEnterRoom_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_okraAx_v3_PmOnEnterRoom_descriptor,
        new java.lang.String[] { "RoomId", "Index", });
    internal_static_org_okraAx_v3_PmOnExitRoom_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_okraAx_v3_PmOnExitRoom_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_okraAx_v3_PmOnExitRoom_descriptor,
        new java.lang.String[] { "RoomId", });
    internal_static_org_okraAx_v3_PmOnChat_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_okraAx_v3_PmOnChat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_okraAx_v3_PmOnChat_descriptor,
        new java.lang.String[] { "Channel", "RoomId", "Message", "From", "FromName", "To", "ToName", });
    org.okraAx.v3.AxAnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
