// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BeanRoomPub.proto

package org.okraAx.v3.beans.roomPub;

public interface MsgChatUserInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.okraAx.v3.MsgChatUserInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 uid = 1;</code>
   */
  long getUid();

  /**
   * <code>optional string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional int32 lv = 3;</code>
   */
  int getLv();
}
