// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BeanRoomPub.proto

package org.okraAx.v3.beans.roomPub;

public interface MsgOnChatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.okraAx.v3.MsgOnChat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *   聊天频道 [0:综合  1:私聊  2:房间]
   * </pre>
   *
   * <code>optional int32 channel = 1;</code>
   */
  int getChannel();

  /**
   * <pre>
   *   发送者
   * </pre>
   *
   * <code>optional .org.okraAx.v3.MsgChatUserInfo from = 2;</code>
   */
  boolean hasFrom();
  /**
   * <pre>
   *   发送者
   * </pre>
   *
   * <code>optional .org.okraAx.v3.MsgChatUserInfo from = 2;</code>
   */
  org.okraAx.v3.beans.roomPub.MsgChatUserInfo getFrom();
  /**
   * <pre>
   *   发送者
   * </pre>
   *
   * <code>optional .org.okraAx.v3.MsgChatUserInfo from = 2;</code>
   */
  org.okraAx.v3.beans.roomPub.MsgChatUserInfoOrBuilder getFromOrBuilder();

  /**
   * <pre>
   * 私聊收信者
   * </pre>
   *
   * <code>optional .org.okraAx.v3.AxAny to = 3;</code>
   */
  boolean hasTo();
  /**
   * <pre>
   * 私聊收信者
   * </pre>
   *
   * <code>optional .org.okraAx.v3.AxAny to = 3;</code>
   */
  org.okraAx.v3.AxAnyProto.AxAny getTo();
  /**
   * <pre>
   * 私聊收信者
   * </pre>
   *
   * <code>optional .org.okraAx.v3.AxAny to = 3;</code>
   */
  org.okraAx.v3.AxAnyProto.AxAnyOrBuilder getToOrBuilder();

  /**
   * <pre>
   *   内容
   * </pre>
   *
   * <code>optional string content = 4;</code>
   */
  java.lang.String getContent();
  /**
   * <pre>
   *   内容
   * </pre>
   *
   * <code>optional string content = 4;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
