// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BeanPlayerRoom.proto

package org.okraAx.v3.beans.roomPub;

public interface PmOnEnterRoomOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.okraAx.v3.PmOnEnterRoom)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *  房间ID
   * </pre>
   *
   * <code>optional int64 roomId = 1;</code>
   */
  long getRoomId();

  /**
   * <pre>
   *  指定位置
   * </pre>
   *
   * <code>optional int32 index = 2;</code>
   */
  int getIndex();
}
