// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BeanPlayerRoom.proto

package org.okraAx.v3.beans.roomPub;

public interface PmOnChatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.okraAx.v3.PmOnChat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *  聊天频道
   * </pre>
   *
   * <code>optional int32 channel = 1;</code>
   */
  int getChannel();

  /**
   * <pre>
   *  房间ID
   * </pre>
   *
   * <code>optional int64 roomId = 2;</code>
   */
  long getRoomId();

  /**
   * <pre>
   *  聊天内容
   * </pre>
   *
   * <code>optional string message = 3;</code>
   */
  java.lang.String getMessage();
  /**
   * <pre>
   *  聊天内容
   * </pre>
   *
   * <code>optional string message = 3;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   *  发送人
   * </pre>
   *
   * <code>optional int64 from = 4;</code>
   */
  long getFrom();

  /**
   * <pre>
   *  发送人名称
   * </pre>
   *
   * <code>optional string fromName = 5;</code>
   */
  java.lang.String getFromName();
  /**
   * <pre>
   *  发送人名称
   * </pre>
   *
   * <code>optional string fromName = 5;</code>
   */
  com.google.protobuf.ByteString
      getFromNameBytes();

  /**
   * <pre>
   *  收信人
   * </pre>
   *
   * <code>optional int64 to = 6;</code>
   */
  long getTo();

  /**
   * <pre>
   *  收信人名称
   * </pre>
   *
   * <code>optional string toName = 7;</code>
   */
  java.lang.String getToName();
  /**
   * <pre>
   *  收信人名称
   * </pre>
   *
   * <code>optional string toName = 7;</code>
   */
  com.google.protobuf.ByteString
      getToNameBytes();
}
