// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FyRoomMessage.proto

package org.okraAx.v3.room.beans;

/**
 * <pre>
 *  加入房间
 * </pre>
 *
 * Protobuf type {@code org.okraAx.v3.VoEnterRoom}
 */
public  final class VoEnterRoom extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.okraAx.v3.VoEnterRoom)
    VoEnterRoomOrBuilder {
  // Use VoEnterRoom.newBuilder() to construct.
  private VoEnterRoom(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private VoEnterRoom() {
    roomId_ = 0;
    seat_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private VoEnterRoom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            roomId_ = input.readInt32();
            break;
          }
          case 16: {

            seat_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.okraAx.v3.room.beans.FyRoomMi.internal_static_org_okraAx_v3_VoEnterRoom_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.okraAx.v3.room.beans.FyRoomMi.internal_static_org_okraAx_v3_VoEnterRoom_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.okraAx.v3.room.beans.VoEnterRoom.class, org.okraAx.v3.room.beans.VoEnterRoom.Builder.class);
  }

  public static final int ROOMID_FIELD_NUMBER = 1;
  private int roomId_;
  /**
   * <pre>
   *  房间
   * </pre>
   *
   * <code>optional int32 roomId = 1;</code>
   */
  public int getRoomId() {
    return roomId_;
  }

  public static final int SEAT_FIELD_NUMBER = 2;
  private int seat_;
  /**
   * <pre>
   *  座位号
   * </pre>
   *
   * <code>optional int32 seat = 2;</code>
   */
  public int getSeat() {
    return seat_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (roomId_ != 0) {
      output.writeInt32(1, roomId_);
    }
    if (seat_ != 0) {
      output.writeInt32(2, seat_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (roomId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, roomId_);
    }
    if (seat_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, seat_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.okraAx.v3.room.beans.VoEnterRoom)) {
      return super.equals(obj);
    }
    org.okraAx.v3.room.beans.VoEnterRoom other = (org.okraAx.v3.room.beans.VoEnterRoom) obj;

    boolean result = true;
    result = result && (getRoomId()
        == other.getRoomId());
    result = result && (getSeat()
        == other.getSeat());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + ROOMID_FIELD_NUMBER;
    hash = (53 * hash) + getRoomId();
    hash = (37 * hash) + SEAT_FIELD_NUMBER;
    hash = (53 * hash) + getSeat();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.okraAx.v3.room.beans.VoEnterRoom parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.okraAx.v3.room.beans.VoEnterRoom parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.okraAx.v3.room.beans.VoEnterRoom parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.okraAx.v3.room.beans.VoEnterRoom parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.okraAx.v3.room.beans.VoEnterRoom parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.okraAx.v3.room.beans.VoEnterRoom parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.okraAx.v3.room.beans.VoEnterRoom parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.okraAx.v3.room.beans.VoEnterRoom parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.okraAx.v3.room.beans.VoEnterRoom parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.okraAx.v3.room.beans.VoEnterRoom parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.okraAx.v3.room.beans.VoEnterRoom prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *  加入房间
   * </pre>
   *
   * Protobuf type {@code org.okraAx.v3.VoEnterRoom}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.okraAx.v3.VoEnterRoom)
      org.okraAx.v3.room.beans.VoEnterRoomOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.okraAx.v3.room.beans.FyRoomMi.internal_static_org_okraAx_v3_VoEnterRoom_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.okraAx.v3.room.beans.FyRoomMi.internal_static_org_okraAx_v3_VoEnterRoom_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.okraAx.v3.room.beans.VoEnterRoom.class, org.okraAx.v3.room.beans.VoEnterRoom.Builder.class);
    }

    // Construct using org.okraAx.v3.room.beans.VoEnterRoom.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      roomId_ = 0;

      seat_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.okraAx.v3.room.beans.FyRoomMi.internal_static_org_okraAx_v3_VoEnterRoom_descriptor;
    }

    public org.okraAx.v3.room.beans.VoEnterRoom getDefaultInstanceForType() {
      return org.okraAx.v3.room.beans.VoEnterRoom.getDefaultInstance();
    }

    public org.okraAx.v3.room.beans.VoEnterRoom build() {
      org.okraAx.v3.room.beans.VoEnterRoom result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.okraAx.v3.room.beans.VoEnterRoom buildPartial() {
      org.okraAx.v3.room.beans.VoEnterRoom result = new org.okraAx.v3.room.beans.VoEnterRoom(this);
      result.roomId_ = roomId_;
      result.seat_ = seat_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.okraAx.v3.room.beans.VoEnterRoom) {
        return mergeFrom((org.okraAx.v3.room.beans.VoEnterRoom)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.okraAx.v3.room.beans.VoEnterRoom other) {
      if (other == org.okraAx.v3.room.beans.VoEnterRoom.getDefaultInstance()) return this;
      if (other.getRoomId() != 0) {
        setRoomId(other.getRoomId());
      }
      if (other.getSeat() != 0) {
        setSeat(other.getSeat());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.okraAx.v3.room.beans.VoEnterRoom parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.okraAx.v3.room.beans.VoEnterRoom) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int roomId_ ;
    /**
     * <pre>
     *  房间
     * </pre>
     *
     * <code>optional int32 roomId = 1;</code>
     */
    public int getRoomId() {
      return roomId_;
    }
    /**
     * <pre>
     *  房间
     * </pre>
     *
     * <code>optional int32 roomId = 1;</code>
     */
    public Builder setRoomId(int value) {
      
      roomId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *  房间
     * </pre>
     *
     * <code>optional int32 roomId = 1;</code>
     */
    public Builder clearRoomId() {
      
      roomId_ = 0;
      onChanged();
      return this;
    }

    private int seat_ ;
    /**
     * <pre>
     *  座位号
     * </pre>
     *
     * <code>optional int32 seat = 2;</code>
     */
    public int getSeat() {
      return seat_;
    }
    /**
     * <pre>
     *  座位号
     * </pre>
     *
     * <code>optional int32 seat = 2;</code>
     */
    public Builder setSeat(int value) {
      
      seat_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *  座位号
     * </pre>
     *
     * <code>optional int32 seat = 2;</code>
     */
    public Builder clearSeat() {
      
      seat_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:org.okraAx.v3.VoEnterRoom)
  }

  // @@protoc_insertion_point(class_scope:org.okraAx.v3.VoEnterRoom)
  private static final org.okraAx.v3.room.beans.VoEnterRoom DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.okraAx.v3.room.beans.VoEnterRoom();
  }

  public static org.okraAx.v3.room.beans.VoEnterRoom getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VoEnterRoom>
      PARSER = new com.google.protobuf.AbstractParser<VoEnterRoom>() {
    public VoEnterRoom parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new VoEnterRoom(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<VoEnterRoom> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<VoEnterRoom> getParserForType() {
    return PARSER;
  }

  public org.okraAx.v3.room.beans.VoEnterRoom getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

