// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FyRoomMessage.proto

package org.okraAx.v3.room.beans;

/**
 * <pre>
 *  准备或取消准备
 * </pre>
 *
 * Protobuf type {@code org.okraAx.v3.VoGetReady}
 */
public  final class VoGetReady extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.okraAx.v3.VoGetReady)
    VoGetReadyOrBuilder {
  // Use VoGetReady.newBuilder() to construct.
  private VoGetReady(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private VoGetReady() {
    uid_ = 0L;
    ready_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private VoGetReady(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            uid_ = input.readInt64();
            break;
          }
          case 16: {

            ready_ = input.readBool();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.okraAx.v3.room.beans.FyRoomMi.internal_static_org_okraAx_v3_VoGetReady_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.okraAx.v3.room.beans.FyRoomMi.internal_static_org_okraAx_v3_VoGetReady_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.okraAx.v3.room.beans.VoGetReady.class, org.okraAx.v3.room.beans.VoGetReady.Builder.class);
  }

  public static final int UID_FIELD_NUMBER = 1;
  private long uid_;
  /**
   * <pre>
   *  唯一uid
   * </pre>
   *
   * <code>optional int64 uid = 1;</code>
   */
  public long getUid() {
    return uid_;
  }

  public static final int READY_FIELD_NUMBER = 2;
  private boolean ready_;
  /**
   * <pre>
   *  准备/取消准备
   * </pre>
   *
   * <code>optional bool ready = 2;</code>
   */
  public boolean getReady() {
    return ready_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (uid_ != 0L) {
      output.writeInt64(1, uid_);
    }
    if (ready_ != false) {
      output.writeBool(2, ready_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (uid_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, uid_);
    }
    if (ready_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, ready_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.okraAx.v3.room.beans.VoGetReady)) {
      return super.equals(obj);
    }
    org.okraAx.v3.room.beans.VoGetReady other = (org.okraAx.v3.room.beans.VoGetReady) obj;

    boolean result = true;
    result = result && (getUid()
        == other.getUid());
    result = result && (getReady()
        == other.getReady());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + UID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUid());
    hash = (37 * hash) + READY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getReady());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.okraAx.v3.room.beans.VoGetReady parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.okraAx.v3.room.beans.VoGetReady parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.okraAx.v3.room.beans.VoGetReady parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.okraAx.v3.room.beans.VoGetReady parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.okraAx.v3.room.beans.VoGetReady parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.okraAx.v3.room.beans.VoGetReady parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.okraAx.v3.room.beans.VoGetReady parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.okraAx.v3.room.beans.VoGetReady parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.okraAx.v3.room.beans.VoGetReady parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.okraAx.v3.room.beans.VoGetReady parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.okraAx.v3.room.beans.VoGetReady prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *  准备或取消准备
   * </pre>
   *
   * Protobuf type {@code org.okraAx.v3.VoGetReady}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.okraAx.v3.VoGetReady)
      org.okraAx.v3.room.beans.VoGetReadyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.okraAx.v3.room.beans.FyRoomMi.internal_static_org_okraAx_v3_VoGetReady_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.okraAx.v3.room.beans.FyRoomMi.internal_static_org_okraAx_v3_VoGetReady_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.okraAx.v3.room.beans.VoGetReady.class, org.okraAx.v3.room.beans.VoGetReady.Builder.class);
    }

    // Construct using org.okraAx.v3.room.beans.VoGetReady.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      uid_ = 0L;

      ready_ = false;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.okraAx.v3.room.beans.FyRoomMi.internal_static_org_okraAx_v3_VoGetReady_descriptor;
    }

    public org.okraAx.v3.room.beans.VoGetReady getDefaultInstanceForType() {
      return org.okraAx.v3.room.beans.VoGetReady.getDefaultInstance();
    }

    public org.okraAx.v3.room.beans.VoGetReady build() {
      org.okraAx.v3.room.beans.VoGetReady result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.okraAx.v3.room.beans.VoGetReady buildPartial() {
      org.okraAx.v3.room.beans.VoGetReady result = new org.okraAx.v3.room.beans.VoGetReady(this);
      result.uid_ = uid_;
      result.ready_ = ready_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.okraAx.v3.room.beans.VoGetReady) {
        return mergeFrom((org.okraAx.v3.room.beans.VoGetReady)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.okraAx.v3.room.beans.VoGetReady other) {
      if (other == org.okraAx.v3.room.beans.VoGetReady.getDefaultInstance()) return this;
      if (other.getUid() != 0L) {
        setUid(other.getUid());
      }
      if (other.getReady() != false) {
        setReady(other.getReady());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.okraAx.v3.room.beans.VoGetReady parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.okraAx.v3.room.beans.VoGetReady) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long uid_ ;
    /**
     * <pre>
     *  唯一uid
     * </pre>
     *
     * <code>optional int64 uid = 1;</code>
     */
    public long getUid() {
      return uid_;
    }
    /**
     * <pre>
     *  唯一uid
     * </pre>
     *
     * <code>optional int64 uid = 1;</code>
     */
    public Builder setUid(long value) {
      
      uid_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *  唯一uid
     * </pre>
     *
     * <code>optional int64 uid = 1;</code>
     */
    public Builder clearUid() {
      
      uid_ = 0L;
      onChanged();
      return this;
    }

    private boolean ready_ ;
    /**
     * <pre>
     *  准备/取消准备
     * </pre>
     *
     * <code>optional bool ready = 2;</code>
     */
    public boolean getReady() {
      return ready_;
    }
    /**
     * <pre>
     *  准备/取消准备
     * </pre>
     *
     * <code>optional bool ready = 2;</code>
     */
    public Builder setReady(boolean value) {
      
      ready_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *  准备/取消准备
     * </pre>
     *
     * <code>optional bool ready = 2;</code>
     */
    public Builder clearReady() {
      
      ready_ = false;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:org.okraAx.v3.VoGetReady)
  }

  // @@protoc_insertion_point(class_scope:org.okraAx.v3.VoGetReady)
  private static final org.okraAx.v3.room.beans.VoGetReady DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.okraAx.v3.room.beans.VoGetReady();
  }

  public static org.okraAx.v3.room.beans.VoGetReady getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VoGetReady>
      PARSER = new com.google.protobuf.AbstractParser<VoGetReady>() {
    public VoGetReady parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new VoGetReady(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<VoGetReady> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<VoGetReady> getParserForType() {
    return PARSER;
  }

  public org.okraAx.v3.room.beans.VoGetReady getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

