// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FyRoomMessage.proto

package org.okraAx.v3.room.beans;

public interface VoLookupRoomOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.okraAx.v3.VoLookupRoom)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 type = 1;</code>
   */
  int getType();
}
